[package]
name = "docker-status"
version = "0.1.0"
authors = ["Aaryanna Simonelli <ashleighsimonelli@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"
tui = "0.3"
shiplift = "0.3"
termion = "*"